# init repository:
#  borgmatic --init --encryption keyfile
#
# export key:
#  borg key export
#
# backup list:
#   borgmatic --list
#
# restore backup:
#   borgmatic --extract --archive dragonfruit-2019-06-07T16:47:36.547867 --restore-path ORIGINALPATH


- name: Install base packages
  apt:
    name: 
      - libssl-dev
      - libacl1-dev
      - libacl1
      - build-essential
      - python3-dev
      - python3-pip
      - python3-msgpack
      - python-setuptools
      - python3-setuptools
      - jq
    state: present

- name: Install required Python Packages
  pip:
    name:
      - borgbackup
      - borgmatic
    executable: pip3

- name: Ensure root has SSH key.
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
  register: root_user

- debug:
    var: root_user['ssh_public_key']


- name: Ensures /etc/borgmatic exists
  file:
    path: /etc/borgmatic
    state: directory
    mode: 0700
    owner: root

- name: Add Borgmatic Configuration
  template:
    src: config.yaml
    dest: "/etc/borgmatic/config.yaml"
    mode: 0600


- name: Add cron-job for borgmatic (large repo, create and check separate)
  block:
    - cron: 
        name: "borgmatic"
        hour: 3
        minute: 0
        user: "root"
        cron_file: borgmatic
        job: "/usr/local/bin/borgmatic -c /etc/borgmatic/config.yaml --create --prune"
    - cron: 
        name: "borgmatic-check"
        day: 1
        hour: 5
        user: "root"
        cron_file: borgmatic
        job: "/usr/local/bin/borgmatic -c /etc/borgmatic/config.yaml --check"

- name: Set PATH for borgmatic cron job.
  cron:
    user: "root"
    cron_file: borgmatic
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: Create folder for SQL dumps
  file:
    path: "{{ db_folder }}"
    state: directory
    mode: '0700'

- name: Copy node exporter textfile generator to system
  template:
    src: borgmatic_exporter
    dest: /usr/local/bin/borgmatic_exporter
    mode: '0755'
  when: use_textfile_collector
    